    
substitutions:
  name: baxter-ac
  friendly_name: Baxter
  #follow_me_sensor: sensor.bedroom_temperature

esphome:
  name: baxter-ac
  #version: "1.0"

esp8266:
  board: wemos_d1_mini32

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "FU7e+9nMG/g6bvtbS0uu1ko7ILeARZDssltz/tIL6UU="

ota:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esphome-Web-6E2922"
    password: "jackson21"

# Must be used once. It is necessary to comment out after the first firmware update.
 use_address: Esphome-Web-6E2922
captive_portal:

#wifi:
 # ssid: !secret wifi_ssid
 # password: !secret wifi_password
  # Must be used once. It is necessary to comment out after the first firmware update.
  #https://github.com/JTO-TN/dudanov
 # use_address: iot-uni-dongle.local

packages:
  remote_package:
    url: https://github.com/JTO-TN/dudanov
    refresh: 0d
    files: [
      # Main dongle package
      hardware/iot-uni-dongle/device.yaml,
      # IR remote transmitter (IR- pad connected to TSOP output of controlled device)
      hardware/iot-uni-dongle/remote/tsop.yaml,
      # IR remote transmitter (IR LED between IR+ and IR- pads)
      #hardware/iot-uni-dongle/remote/led.yaml,
      # Electrolux EACS. Select your model HERE.
      climate/midea/electrolux.yaml,

      # "Flash" button. Run `button_click` script on click.
      hardware/iot-uni-dongle/button.yaml,
      # Toggles power on button click. (Not working yet. Support will be in next ESPHome release 2022.6)
      climate/midea/common/button_action/power.yaml,

      # "Beeper feedback" switch
      climate/midea/common/beeper.yaml,
      # "Display toggle" button. Works only via IR transmitter for Electrolux EACS.
      climate/midea/common/display.yaml,
      # "Swing step" button. Works only via IR transmitter.
      climate/midea/common/swing.yaml,
      # "FollowMe" capability via HomeAssistant service.
      climate/midea/common/follow_me/service.yaml,
      # "FollowMe" capability via HomeAssistant sensor.
      # Sensor entity name setting up via ${follow_me_sensor} substitution.
      #climate/midea/common/follow_me/sensor.yaml,
    ]
