# Default iot-uni-dongle config
substitutions:
  name: iot-uni-dongle

packages:
  # Default device config
  default: !include ../../common/default.yaml
  # Status light on ESP-12F module
  status: !include ../esp12e/status-light.yaml

# Define ESP-12F module
esp8266:
  board: esp12e

# Disable logging via UART
logger:
  baud_rate: 0

# UART config
uart:
  tx_pin: GPIO1
  rx_pin: GPIO3
  baud_rate: 9600
