substitutions:
  friendly_name: IoT Device

packages:
  # Minimal iot-uni-dongle config
  minimal: !include minimal.yaml
  # Default common config
  default: !include ../../common/default.yaml
  # Status light on ESP-12F module
  status: !include ../esp12e/status-light.yaml
