# Default iot-uni-dongle config
substitutions:
  name: iot-uni-dongle

packages:
  main: !include ../../common/main.yaml

# Board config
esp8266:
  board: esp12e

# Disable logging via UART
logger:
  baud_rate: 0

# UART config
uart:
  tx_pin: GPIO1
  rx_pin: GPIO3
  baud_rate: 9600
