# Minimal iot-uni-dongle config
substitutions:
  name: iot-uni-dongle

packages:
  # Main device config
  main: !include ../../common/main.yaml

# Define ESP-12F module
esp8266:
  board: esp01
  restore_from_flash: true

# Disable logging via UART
logger:
  baud_rate: 0

# Example configuration entry
uart:
  tx_pin: GPIO1
  rx_pin: GPIO3
  baud_rate: 9600
  debug:
    direction: BOTH
    dummy_receiver: false
    after:
      delimiter: "\n"
    sequence:
      - lambda: UARTDebug::log_string(direction, bytes);
