# Default names
substitutions:
  name: my-switch
  friendly_name: My Switch

# Define ESP32D4-PICO chip
esp32:
  board: esp32dev

# Onboard status led
status_led:
  pin: GPIO32

# Adds two main switch keys
binary_sensor:
  - platform: gpio
    name: "${friendly_name} Key 1"
    icon: mdi:electric-switch
    id: key1
    pin:
      number: GPIO0
      inverted: true
    filters:
      - delayed_on_off: 50ms
  - platform: gpio
    name: "${friendly_name} Key 2"
    icon: mdi:electric-switch
    id: key2
    pin:
      number: GPIO33
      inverted: true
    filters:
      - delayed_on_off: 50ms

# Buzzer ledc output
output:
  - platform: ledc
    id: buzzer_out
    pin: GPIO4

# RTTL player
rtttl:
  output: buzzer_out

# RTTL service
api:
  services:
    - service: play_rtttl
      variables:
        song: string
      then:
        - rtttl.play:
            rtttl: !lambda 'return song;'

packages:
  # Default device template
  default: !include ../../common/default.yaml
